In [1]:
print("Hello World")

Hello World


In [2]:
import numpy as np
print(np.array([1,2,3]))

[1 2 3]


In [3]:
mylist = np.array([1,2,3,4,5])
print(mylist)

[1 2 3 4 5]


In [4]:
mylist

array([1, 2, 3, 4, 5])

In [5]:
type(mylist)

numpy.ndarray

In [6]:
n1 = np.zeros((1,2))

In [7]:
n1

array([[0., 0.]])

In [8]:
n2 = np.zeros((2,3))

In [9]:
n2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.arange(1,5)

array([1, 2, 3, 4])

In [11]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [12]:
np.random.randint(1,100,5)

array([12, 56, 61, 55, 94])

In [13]:
np.random.randint(1,100,10)

array([58, 54, 41, 73, 74, 75, 53, 37, 73, 29])

In [14]:
n1 = np.array([[1,2,3],[4,5,6]])

In [15]:
n1.shape

(2, 3)

In [16]:
n1.shape = (6,1)

In [17]:
n1

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [18]:
n1 = np.array([1,2,3])
n2 = np.array([4,5,6])

In [19]:
np.vstack((n1,n2))

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
np.hstack((n1,n2))

array([1, 2, 3, 4, 5, 6])

In [21]:
np.column_stack((n1,n2))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [22]:
n1 = np.array([10,20,30,40,50,60])
n2 = np.array([50,60,70,80,90])

In [23]:
np.intersect1d(n1,n2)

array([50, 60])

In [24]:
np.setdiff1d(n1,n2)

array([10, 20, 30, 40])

In [25]:
n1 = np.array([10,20])
n2 = np.array([30,40])

In [26]:
np.sum([n1,n2])

100

In [27]:
np.sum([n1,n2],axis=0)

array([40, 60])

In [28]:
np.sum([n1,n2],axis=1)

array([30, 70])

In [29]:
#Basic operations

In [30]:
n1 = np.array([1,2,3,4,5])

In [31]:
n1 = n1*2

In [32]:
n1

array([ 2,  4,  6,  8, 10])

In [33]:
n1+=1

In [34]:
n1

array([ 3,  5,  7,  9, 11])

In [35]:
n1= np.array([10,20,30,40,50,60])

In [36]:
n1

array([10, 20, 30, 40, 50, 60])

In [37]:
np.mean(n1)

35.0

In [38]:
np.median(n1)

35.0

In [39]:
np.std(n1)

17.07825127659933

In [40]:
n1 = np.array([1,1,1,2,3,2])

In [41]:
np.save('numpy_arr',n1)

In [42]:
np.load('numpy_arr.npy')

array([1, 1, 1, 2, 3, 2])

In [43]:
import pandas as pd

In [44]:
s1 = pd.Series([1,2,3,4,5])
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [45]:
s1 = pd.Series([1,2,3], index=['a','b','c'])


In [46]:
s1

a    1
b    2
c    3
dtype: int64

In [47]:
pd.Series({'a':10,'b':20,'c':30})

a    10
b    20
c    30
dtype: int64

In [48]:
s1= pd.Series([1,2,3,4,5,6,7,8])
s1[3]

4

In [49]:
s1[:4]

0    1
1    2
2    3
3    4
dtype: int64

In [50]:
pd.DataFrame({'Name':['Anne','Bob','Matt'],'Marks':[75,12,82]})

Name  Marks
0  Anne     75
1   Bob     12
2  Matt     82

In [51]:
print("Hello")

Hello


In [52]:
pd.Series([1,2,3,4])

0    1
1    2
2    3
3    4
dtype: int64

In [57]:
iris = pd.read_csv('Iris.csv')

In [58]:
iris.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [59]:
iris.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [60]:
iris.iloc[0:3,0:2]

Id  SepalLengthCm
0   1            5.1
1   2            4.9
2   3            4.7

In [62]:
iris.loc[0:10,('SepalLengthCm','PetalLengthCm')]

SepalLengthCm  PetalLengthCm
0             5.1            1.4
1             4.9            1.4
2             4.7            1.3
3             4.6            1.5
4             5.0            1.4
5             5.4            1.7
6             4.6            1.4
7             5.0            1.5
8             4.4            1.4
9             4.9            1.5
10            5.4            1.5

In [63]:
iris.min()

Id                         1
SepalLengthCm            4.3
SepalWidthCm               2
PetalLengthCm              1
PetalWidthCm             0.1
Species          Iris-setosa
dtype: object

In [65]:
iris[['SepalLengthCm','PetalLengthCm']].apply(lambda x:x*2)[0:10]

SepalLengthCm  PetalLengthCm
0           10.2            2.8
1            9.8            2.8
2            9.4            2.6
3            9.2            3.0
4           10.0            2.8
5           10.8            3.4
6            9.2            2.8
7           10.0            3.0
8            8.8            2.8
9            9.8            3.0

In [ ]:
iris.