In [1]:
print("Hello World")

Hello World


In [7]:
import numpy as np
print(np.array([1,2,3]))

[1 2 3]


In [8]:
mylist = np.array([1,2,3,4,5])
print(mylist)

[1 2 3 4 5]


In [9]:
mylist

array([1, 2, 3, 4, 5])

In [13]:
type(mylist)

numpy.ndarray

In [14]:
n1 = np.zeros((1,2))

In [15]:
n1

array([[0., 0.]])

In [16]:
n2 = np.zeros((2,3))

In [17]:
n2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.arange(1,5)

array([1, 2, 3, 4])

In [19]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [21]:
np.random.randint(1,100,5)

array([91, 68, 46, 40, 41])

In [22]:
np.random.randint(1,100,10)

array([77, 46, 27, 57, 17, 90, 66, 76, 75, 66])

In [23]:
n1 = np.array([[1,2,3],[4,5,6]])

In [24]:
n1.shape

(2, 3)

In [25]:
n1.shape = (6,1)

In [26]:
n1

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [27]:
n1 = np.array([1,2,3])
n2 = np.array([4,5,6])

In [28]:
np.vstack((n1,n2))

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
np.hstack((n1,n2))

array([1, 2, 3, 4, 5, 6])

In [30]:
np.column_stack((n1,n2))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [31]:
n1 = np.array([10,20,30,40,50,60])
n2 = np.array([50,60,70,80,90])

In [32]:
np.intersect1d(n1,n2)

array([50, 60])

In [33]:
np.setdiff1d(n1,n2)

array([10, 20, 30, 40])

In [35]:
n1 = np.array([10,20])
n2 = np.array([30,40])

In [36]:
np.sum([n1,n2])

100

In [37]:
np.sum([n1,n2],axis=0)

array([40, 60])

In [38]:
np.sum([n1,n2],axis=1)

array([30, 70])

In [39]:
#Basic operations

In [40]:
n1 = np.array([1,2,3,4,5])

In [41]:
n1 = n1*2

In [42]:
n1

array([ 2,  4,  6,  8, 10])

In [43]:
n1+=1

In [44]:
n1

array([ 3,  5,  7,  9, 11])

In [45]:
n1= np.array([10,20,30,40,50,60])

In [46]:
n1

array([10, 20, 30, 40, 50, 60])

In [47]:
np.mean(n1)

35.0

In [48]:
np.median(n1)

35.0

In [50]:
np.std(n1)

17.07825127659933

In [53]:
n1 = np.array([1,1,1,2,3,2])

In [58]:
np.save('numpy_arr',n1)

In [59]:
np.load('numpy_arr.npy')

array([1, 1, 1, 2, 3, 2])