In [1]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import style
style.use('ggplot')

from sklearn.cluster import KMeans


In [2]:
np.random.seed(0)
x = [ np.random.randint(0,2) for _ in range(50) ]
y = [ np.random.randint(0,2) for _ in range(50) ]
z = [ np.random.randint(0,2) for _ in range(50) ]
a = [ np.random.randint(0,2) for _ in range(50) ]

print('X: ',x)
print('Y: ',y)
print('Z: ',z)
print('A: ',a)

X:  [0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1]
Y:  [0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0]
Z:  [1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1]
A:  [0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0]


In [3]:
X= np.array((x,y,z,a)).T
print(X)
X.shape

[[0 0 1 0]
 [1 1 0 0]
 [1 1 0 0]
 [0 1 1 1]
 [1 1 0 0]
 [1 0 0 1]
 [1 1 0 1]
 [1 0 1 1]
 [1 0 1 0]
 [1 1 0 1]
 [1 1 1 0]
 [0 0 0 0]
 [0 1 0 1]
 [1 0 0 0]
 [0 1 0 1]
 [0 0 0 1]
 [0 0 1 0]
 [0 0 0 0]
 [0 0 1 1]
 [1 0 0 0]
 [0 1 1 1]
 [1 1 1 0]
 [1 0 1 1]
 [0 0 1 0]
 [0 0 1 1]
 [1 1 0 0]
 [1 1 1 1]
 [1 0 1 0]
 [1 1 1 0]
 [0 0 1 0]
 [1 0 0 1]
 [0 1 1 0]
 [1 0 1 1]
 [0 1 0 0]
 [1 1 0 1]
 [1 1 1 0]
 [0 1 0 0]
 [1 1 0 0]
 [1 1 0 0]
 [0 0 0 0]
 [0 1 1 1]
 [1 1 1 0]
 [0 0 0 0]
 [1 0 0 1]
 [1 1 1 0]
 [1 0 0 0]
 [1 0 1 0]
 [1 1 1 1]
 [0 1 1 0]
 [1 0 1 0]]


(50, 4)

In [5]:
kmeans = KMeans(n_clusters=4,max_iter=300)
kmeans.fit(X)

centroids = kmeans.cluster_centers_
labels = kmeans.labels_

print(centroids)
print("\n\n")


print(labels)
print("\n\n")

#colors = ['g.', 'r.', 'y.', 'c.']

for i in range(len(X)):
    if labels[i] == 0:
        print('Coordinate: ', X[i], 'label: ', labels[i])

[[3.12500000e-01 4.37500000e-01 1.00000000e+00 6.25000000e-01]
 [1.00000000e+00 6.00000000e-01 1.00000000e+00 5.55111512e-17]
 [6.92307692e-01 1.00000000e+00 1.11022302e-16 3.84615385e-01]
 [5.45454545e-01 1.11022302e-16 1.11022302e-16 3.63636364e-01]]



[0 2 2 0 2 3 2 0 1 2 1 3 2 3 2 3 0 3 0 3 0 1 0 0 0 2 0 1 1 0 3 0 0 2 2 1 2
 2 2 3 0 1 3 3 1 3 1 0 0 1]



Coordinate:  [0 0 1 0] label:  0
Coordinate:  [0 1 1 1] label:  0
Coordinate:  [1 0 1 1] label:  0
Coordinate:  [0 0 1 0] label:  0
Coordinate:  [0 0 1 1] label:  0
Coordinate:  [0 1 1 1] label:  0
Coordinate:  [1 0 1 1] label:  0
Coordinate:  [0 0 1 0] label:  0
Coordinate:  [0 0 1 1] label:  0
Coordinate:  [1 1 1 1] label:  0
Coordinate:  [0 0 1 0] label:  0
Coordinate:  [0 1 1 0] label:  0
Coordinate:  [1 0 1 1] label:  0
Coordinate:  [0 1 1 1] label:  0
Coordinate:  [1 1 1 1] label:  0
Coordinate:  [0 1 1 0] label:  0
